baseURL = 'https://emrecankoc6.github.io/Literaconite/'
languageCode = 'en-us'
title = 'Literaconite'
theme = 'PaperMod'

[params]
    env = "production"
    defaultTheme = "dark"
    disableThemeToggle = true
    mainSections = ["poetry", "review"]

[[menu.main]]
    name = "Poetry"
    url = "poetry/"
    weight = 10
[[menu.main]]
    name = "Reviews"
    url = "review/"
    weight = 20
